spring:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  datasource:
    # MySQL
    driver-class-name: com.mysql.jdbc.Driver
    # DB Source URL
    # DB username
    username: root
    # DB password
    password: 293648ak!
    # 처리시 발생하는 쿼리문을 보여줄 것인지
    url: jdbc:mysql://localhost:3306/mbtitest


  management:
    endpoints:
      web:
        exposure:
          include: '*'

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html