
spring:

  jpa:
    # 처리시 발생하는 쿼리문을 보여줄 것인지
    show-sql: true
    hibernate:
      # 테이블 자동 생성 방식
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  datasource:
    # MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver
    # DB username
    username: root
    # DB password
    password: 293648ak
    # DB Source URL
    # url: jdbc:mysql://localhost:3306/mbtitest
    url: jdbc:mysql://mbtitest.cfqhgs70crvg.ap-northeast-2.rds.amazonaws.com:3306/mbtitest
    dbcp2:
      test-on-borrow: true
      validation-query: select 1


  management:
    endpoints:
      web:
        exposure:
          include: '*'

  # 타임 리프
  #thymeleaf:
    #prefix: classpath:templates/
    #suffix: .html

  # spring security - 소셜 로그인(카카오)
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: cd517171875d57e47b7e6c334b4ebbfb
            client-secret: hUrq8zcPP6uDCJxcjC7xWd6WVMjeYp70
            #redirect-uri: http://localhost/login/oauth2/code/kakao
            redirect-uri: http://mbtitestbypeople.link/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao # Spring 내에서 인식할 OAuth2 Provider Name
            scope: profile_nickname, account_email #동의항목
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize # authorization code 얻는 API
            token-uri: https://kauth.kakao.com/oauth/token # access token을 얻는 API
            user-info-uri: https://kapi.kakao.com/v2/user/me # 유저 정보 조회 API
            user-name-attribute: id # userInfo API Response에서 얻어올 ID 프로퍼티

# SQL 쿼리문 확인용 p6spy 설정
decorator:
  datasource:
    p6spy:
      enable-logging: true
