spring:

  jpa:
    # 처리시 발생하는 쿼리문을 보여줄 것인지
    show-sql: true
    hibernate:
      # 테이블 자동 생성 방식
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  datasource:
    # MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver
    # DB username
    username: root
    # DB password
    password: 293648ak!
    # DB Source URL
    url: jdbc:mysql://localhost:3306/mbtitest


  management:
    endpoints:
      web:
        exposure:
          include: '*'

  # 타임 리프
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html